##################################################################
#                    College Persistence                         #
#                        Test YAML file                          #
#   Runs a tiny experiment so you can see if it goes through.    # 
#    It writes output plots and logs to [...]/test_modeling_log  # 
#   For more documentation and options, see the default.yaml     #
##################################################################


############################
# Sliding window setup     #
############################
earliest_train_start: 2011-09-01
latest_train_start: 2011-09-01
train_period_months: 12
test_period_months: 12
time_steps_months: 12


########################################################
# Model selection                                      #

########################################################
models:
- LogisticRegression:
   implementation: scikit
   penalty: [l2]
   C: [1.0]


############################
# Feature lists            #
############################
features:
-
 - StudentGender
 - avgYear11_12UnweightedGPA

############################
# Feature products         #
############################
products:

############################
# Target variable          #
############################
target:
- PersistThreeSemesters

############################
# Sample selection         #
############################
sample: 
- PersistTwoSemesters: =True
- DegreeType: ='Bachelors'
- NetworkNoble: =True

############################
# Misc         #
############################ 
nan_handling: lax


############################
# Output                   #
############################
looplog: 'looplog.md'
logFolder: test_modeling_log
summary_only: False
