##################################################################
#                    College Persistence                         #
#       This is the default config for visutil.get_df()          #
##################################################################

############################
# Date Setup               #
############################

start_date: 2010-01-01
end_date: 2015-01-01

############################
# Feature lists            #
############################
features:
- StudentAgeAtEnrollment
# - StudentEthnicity
# - StudentGender
# - HighSchoolMostRecentlyAttended
- AlumsEverAttendedSpecificCollege
# - historicallyBlackCollege
# - sixYearMinorityTransferRate
# - sixYearTransferRate
- sixYearMinorityGraduationRate
- sixYearGraduationRate
# - isForProfit
# - isPrivate
- finalUnweightedGPA
- highestCompositeACT
- numberAPsYear12
- numberAPsYear11
- numberAPsYear10
- numberHonsYear12
- numberHonsYear11
- numberHonsYear10
- maxRankYear12
- maxRankYear11
- maxRankYear10
- minRankYear12
- minRankYear11
- minRankYear10
- avgRankYear12
- avgRankYear11
- avgRankYear10
- totalNumberofContacts
# - ContactMediumPercentages
# - everSpecialEd
# - everFreeLunch
# - isFirstGen
# - degreeSubject
# - IsFirstEnrollment
# - SpringEnrollment
- AvgHSAway
- AvgHSTardy
- AvgHSUnexcused
- AvgHSExcused
- AvgHSSuspended
- AvgHSEarlyDismissal
# - AvgMSAway
# - AvgMSTardy
# - AvgMSUnexcused
# - AvgMSExcused
# - AvgMSSuspended
# - AvgMSEarlyDismissal
# - is4year
# - CollegeName
# - barronsSelectivity
# - distanceFromChicago
- percentAccepted
- percentEnroll
# - percentFemale
- percentAfricanAmerican
- percentHispanic
# - percentInState
- percentPellGrant
- avgNetPrice
- netPrice0_30
- netPrice30_48
- netPrice48_75
# - locale
# - sizeRange
- year12GPA
- year11GPA
- year10GPA
- year9GPA
- ChangeInUnweightedGPA
- avgYear11_12UnweightedGPA
- avgYear9_10UnweightedGPA


############################
# Target variable          #
############################
target:
- PersistThreeSemesters

############################
# Sample selection         #
############################
sample: # TODO figure out what to pass here / is it safe / what's a good idea?
- PersistTwoSemesters: =True
- DegreeType: ='Bachelors'
- NetworkKIPPNJ: =False
- NetworkNoble: =True

schema: common